queues:
  triagem:
    type: M/M/2/10  # 2 atendentes, capacidade 10
    arrival:
      min: 5  # tempo mínimo entre chegadas (minutos)
      max: 15  # tempo máximo entre chegadas (minutos)
    service:
      min: 3  # tempo mínimo de atendimento (minutos)
      max: 8  # tempo máximo de atendimento (minutos)
    routing:
      - emergencia: 0.3  # 30% vai para emergência
      - consulta: 0.7    # 70% vai para consulta

  emergencia:
    type: M/M/3/8  # 3 médicos, capacidade 8
    arrival:
      min: 0  # não recebe chegadas externas
      max: 0
    service:
      min: 15  # tempo mínimo de atendimento (minutos)
      max: 45  # tempo máximo de atendimento (minutos)
    routing:
      - alta: 0.6     # 60% recebe alta
      - internacao: 0.4  # 40% vai para internação

  consulta:
    type: M/M/2/12  # 2 médicos, capacidade 12
    arrival:
      min: 0  # não recebe chegadas externas
      max: 0
    service:
      min: 10  # tempo mínimo de atendimento (minutos)
      max: 30  # tempo máximo de atendimento (minutos)
    routing:
      - alta: 0.7     # 70% recebe alta
      - internacao: 0.3  # 30% vai para internação

  internacao:
    type: M/M/1/6  # 1 servidor, capacidade 6
    arrival:
      min: 0  # não recebe chegadas externas
      max: 0
    service:
      min: 120  # tempo mínimo de internação (minutos)
      max: 240  # tempo máximo de internação (minutos)
    routing:
      - alta: 1.0  # 100% recebe alta após internação

  alta:
    type: M/M/1/20  # 1 servidor, capacidade 20
    arrival:
      min: 0  # não recebe chegadas externas
      max: 0
    service:
      min: 2  # tempo mínimo de processamento da alta (minutos)
      max: 5  # tempo máximo de processamento da alta (minutos)
    routing: []  # fim do processo 